[package]
name = "noteworthy"
version = "0.1.0"
authors = ["Dave Patrick <davecruz48@gmail.com>"]
license = "GPL-3.0-or-later"
edition = "2018"

[dependencies]
log = "0.4"
pretty_env_logger = "0.4"
gettext-rs = { version = "0.7", features = ["gettext-system"] }
once_cell = "1.5"
sourceview = { package = "sourceview5", version = "0.3.0" }
gtk = { package = "gtk4", version = "0.3" }
adw = { package = "libadwaita", version = "0.1.0-alpha-3" }

anyhow = "1.0.44"
indexmap = { version = "1.7.0", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_yaml = "0.8"
gray_matter = "0.2"

git2 = "0.13"
