on:
  push:
    branches: [main]
  pull_request:

name: CI

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
      - uses: crate-ci/typos@v1.0.4
      - name: Create blank versions of configured file
        run: echo -e "" >> src/config.rs
      - name: Run checks.py
        run: python build-aux/checks.py --verbose

  codespell:
    name: Codespell
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          ignore_words_list: "crate,ser"
          skip: "*.svg,*.po"

  flatpak:
    name: Flatpak
    runs-on: ubuntu-20.04
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-nightly
      options: --privileged
    steps:
    - uses: actions/checkout@v2
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
      with:
        bundle: noteworthy.flatpak
        manifest-path: build-aux/io.github.seadve.Noteworthy.Devel.json
        run-tests: true
        cache-key: flatpak-builder-${{ github.sha }}
